apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitoring
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: apps-ingress-jaba
    #service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    #service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    #service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '3600'
    cert-manager.io/issuer: letsencrypt-http01-prod
spec:
  ingressClassName: external-nginx
  tls:
  - hosts:
    - grafanav1.monitoring.devopstech.net
    secretName: grafanav1-monitoring-devopstech-net-key-pair
  rules:
  - host: grafanav1.monitoring.devopstech.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-grafana
            port:
              number: 80
