apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: flux-system
spec:
  releaseName: istio-base
  serviceAccountName: helm-controller
  targetNamespace: istio-system
  interval: 5m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: base
      version: 1.19.0
      sourceRef:
        kind: HelmRepository
        name: istio-charts
        namespace: flux-system
      interval: 1m
  #values:
#  base:
#     enableCRDTemplates: true
