apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: flux-system
spec:
  releaseName: istiod
  serviceAccountName: helm-controller
  targetNamespace: istio-system
  interval: 5m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  dependsOn:
  - name: istio-base
  chart:
    spec:
      chart: istiod
      version: 1.17.1
      sourceRef:
        kind: HelmRepository
        name: istio-charts
        namespace: flux-system
      interval: 1m
  values:
    telemetry:
      enabled: true
    global:
      istioNamespace: istio-system
    meshConfig:
      ingressService: istio-gateway
      ingressSelector: gateway
