apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: flux-system
spec:
  releaseName: istio-base
  serviceAccountName: helm-controller
  targetNamespace: istio-system
  interval: 5m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: base
      version: 1.17.1
      sourceRef:
        kind: HelmRepository
        name: istio-charts
        namespace: flux-system
      interval: 1m
  values:
    global:
      istioNamespace: istio-system
#  base:
#     enableCRDTemplates: true
