apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gateway
  namespace: flux-system
spec:
  releaseName: gateway
  serviceAccountName: helm-controller
  targetNamespace: istio-ingress
  interval: 5m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: gateway
      version: 1.19.0
      sourceRef:
        kind: HelmRepository
        name: istio-charts
        namespace: flux-system
      interval: 1m
  values:
    labels:
      istio: ingressgateway
