apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-operator
  namespace: flux-system
spec:
  releaseName: istio-operator
  serviceAccountName: helm-controller
  targetNamespace: istio-system
  interval: 5m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: ./manifests/charts/istio-operator
      version: 1.19.0
      sourceRef:
        kind: GitRepository
        name: istio-operator-charts
        namespace: flux-system
      interval: 1m
  values:
    watchedNamespaces: "istio-system,istio-ingress"
