apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: flux-system
spec:
  releaseName: istiod
  serviceAccountName: helm-controller
  targetNamespace: istio-system
  interval: 5m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  # dependsOn:
  # - name: istio-base
  #   namespace: istio-system
  chart:
    spec:
      chart: istiod
      version: 1.19.0
      sourceRef:
        kind: HelmRepository
        name: istio-charts
        namespace: flux-system
      interval: 1m
