apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingressgateway
  namespace: flux-system
spec:
  releaseName: ingressgateway
  serviceAccountName: helm-controller
  targetNamespace: istio-ingress
  interval: 5m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: gateway
      version: 1.19.0
      sourceRef:
        kind: HelmRepository
        name: istio-charts
        namespace: flux-system
      interval: 1m
  values:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-internal: "false"
      kubernetes.io/role/elb: 1
    labels:
      istio: ingressgateway
      app: ingressgateway
