apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: prod-cluster-issuer
  namespace: production
spec:
  acme:
    # Staging Environment: must be used for testing before using prod env
    # Letsencrypt has a strict rate limit.
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: prod-cluster-issuer
    solvers:
    - selector: {}
      http01:
        ingress:
          class: istio
