apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: devopstech-certificate
  namespace: istio-system
spec:
  secretName: devopstech-certificate-secret
  commonName: test.monitoring.devopstech.net
  dnsNames:
  - test.monitoring.devopstech.net
  issuerRef:
    name: letsencrypt-prod-cluster
    kind: ClusterIssuer
    group: cert-manager.io

