apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-devopstech-net-cert
  namespace: istio-ingress
spec:
  secretName: ingress-devopstech-net-cert
  commonName: test.monitoring.devopstech.net
  dnsNames:
  - test.monitoring.devopstech.net
  issuerRef:
    name: prod-cluster-issuer
    kind: Issuer
    group: cert-manager.io
