apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-devopstech-net-cert
  namespace: istio-ingress
spec:
  secretName: ingress-devopstech-net-cert
  commonName: test.monitoring.devopstech.net
  dnsNames:
  - test.monitoring.devopstech.net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    #group: cert-manager.io
  acme:
    config:
    - http01:
        ingressClass: istio
      domains:
      - test.monitoring.devopstech.net
