apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-devopstech-net-cert
  namespace: production
spec:
  secretName: ingress-devopstech-net-cert
  commonName: test.monitoring.devopstech.net
  dnsNames:
  - test.monitoring.devopstech.net
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
    group: cert-manager.io

