apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: devopstech-certificate
  namespace: istio-ingress
  #annotations:
#cert-manager.io/issue-temporary-certificate: "true"
spec:
  secretName: devopstech-certificate-secret
  commonName: test.monitoring.devopstech.net
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
  - server auth
  - client auth
  dnsNames:
  - test.monitoring.devopstech.net
  issuerRef:
    name: letsencrypt-prod-cluster
    kind: ClusterIssuer
    group: cert-manager.io

