apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-devopstech-net
  namespace: istio-ingress
spec:
  secretName: api-devopstech-net-crt
  dnsNames:
  - test.monitoring.devopstech.net
  issuerRef:
    name: staging-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
