apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 0.namespace.yaml
- 1.deploymentv1.yaml
- 2.deploymentv2.yaml
- 3.myappservice.yaml
#- 4.destinationrule.yaml
#- 5.virtualservice.yaml
- 6.gateway.yaml
- 7.cluster-issuer-prod.yaml
- 7.cluster-issuer-staging.yaml
- 8.certificate.yaml
#- 9.ingress.yaml
