apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-cloudcamp
  namespace: flux-system
spec:
  releaseName: cert-cloudcamp
  serviceAccountName: helm-controller
  targetNamespace: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: 1.13.1
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  interval: 2m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    installCRDs: true
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
        prometheusInstance: kube-prometheus-stack
        labels:
          release: kube-prometheus-stack
    #extraArgs:
#- --feature-gates=ExperimentalGatewayAPISupport=true


