apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-cloudcamp
  namespace: flux-system
spec:
  releaseName: cert-cloudcamp
  serviceAccountName: helm-controller
  targetNamespace: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: 1.5.3
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  interval: 2m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
        namespace: cert-manager
        prometheusInstance: kube-prometheus-stack
        labels:
          release: kube-prometheus-stack


