apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-http01-prod
  namespace: game-2048
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jbadrian@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-http01-key-pair
    solvers:
    - http01:
        ingress:
          class: external-nginx
