apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: flux-system
spec:
  releaseName: aws-load-balancer-controller
  serviceAccountName: aws-load-balancer-controller
  targetNamespace: kube-system
  interval: 1m
  chart:
    spec:
      chart: aws-load-balancer-controller
      #version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: eks-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # values replaced with values on ConfigMap external-config-data
    #serviceAccount:
    #  annotations:
    #    eks.amazonaws.com/role-arn: arn:aws:iam::628924030472:role/AmazonEKSLoadBalancerControllerRole2
    clusterName: vcc-eksctl
