apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    # values replaced with values on ConfigMap external-config-data
    eks.amazonaws.com/role-arn: ${awsLoadBalancerControllerIamRoleArn}
