apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
- eks-charts-helm.yaml
- nginx-ingress-controller.yaml
- prometheus.yaml
- flagger.yaml
- cert-manager.yaml
