apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-ebs-csi-driver
  namespace: flux-system
spec:
  releaseName: aws-ebs-csi-driver
  serviceAccountName: ebs-csi-controller-irsa
  targetNamespace: kube-system
  chart:
    spec:
      chart: aws-ebs-csi-driver
      version: 2.23.0
      sourceRef:
        kind: HelmRepository
        name: aws-ebs-csi-driver
        namespace: flux-system
  interval: 2m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    # values replaced with values on ConfigMap external-config-data
    serviceAccount:
      controller:
        create: false
        name: ebs-csi-controller-irsa
      snapshot:
        create: false
        name: ebs-csi-controller-irsa
    enableVolumeScheduling: true
    enableVolumeSnapshot: true


