apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: ebs-csi-controller-irsa
  name: ebs-csi-controller-irsa
  namespace: kube-system
  annotations:
    # values replaced with values on ConfigMap external-config-data
    eks.amazonaws.com/role-arn: ${awsCSIDriverIamRoleArn}
