apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio-addons
  namespace: flux-system
spec:
  interval: 10m0s
  serviceAccountName: kustomize-controller
  path: ./infrastructure/base/addons/istio-addons
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
