apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio-apps
  namespace: flux-system
spec:
  interval: 5m0s
  serviceAccountName: kustomize-controller
  dependsOn:
  - name: infrastructure
  path: ./apps/istio
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
